### ISSUE TITLE
Local Testing install error

### ISSUE THREAD

**Issue by songproducer** [mwmbl/mwmbl#106]
Hello,

When I run:

DATABASE_URL="postgres://postgres@" python -m mwmbl.main

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leotreasure/mwmbl/mwmbl/main.py", line 15, in <module>
    from mwmbl.platform import user
  File "/Users/leotreasure/mwmbl/mwmbl/platform/user.py", line 14, in <module>
    LEMMY_URL = os.environ["LEMMY_URL"]
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'LEMMY_URL'

```

Not sure what to set LEMMY_URL to.

**Comment by daoudclarke** [comment]
Yeah, this is an old dependency that needs to be removed - thanks for mentioning.

**Comment by diagonalo** [comment]
This should be fixed by the updated documentation.

**Comment by Kreijstal** [comment]
> I think this is currently not up to date. Probably close.

The issue or the repo?
