### ISSUE TITLE
app is None when running tinysearchenginer server with python -m mwmbl.tinysearchengine.app

### ISSUE THREAD

**Issue by nitred** [mwmbl/mwmbl#30]
Reported first by @daoudclarke and I've verified as well that tinesearchengine server works fine when using the binary/entrypoint:
`mwmbl-tinysearchengine --config config/tinysearchengine.yaml`

However it fails when running the module as a script using
`python -m mwmbl.tinysearchengine.app --config config/tinysearchengine.yaml`

The following error message is raised:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/nitred/anaconda3/envs/mwmbl/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/nitred/anaconda3/envs/mwmbl/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/nitred/anaconda3/envs/mwmbl/lib/python3.9/site-packages/uvicorn/middleware/asgi2.py", line 16, in __call__
    instance = self.app(scope)
TypeError: 'NoneType' object is not callable
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/nitred/anaconda3/envs/mwmbl/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/nitred/anaconda3/envs/mwmbl/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/nitred/anaconda3/envs/mwmbl/lib/python3.9/site-packages/uvicorn/middleware/asgi2.py", line 16, in __call__
    instance = self.app(scope)
TypeError: 'NoneType' object is not callable
```

**Comment by nitred** [comment]
The issue has started to occur because of the changes made to `app.py` in #24 and not due to the introduction of binary/entrypoints. The global `app` variable was always initialized with a FastAPI instance using hard coded config params and therefore was never None. However due to the introduction of a config file in #24, the global `app` variable has to be None until runtime and a FastAPI instance is created at runtime from the user provided config file and set at the global variable.

When using `python -m mwmbl.tinysearchengine.app` calling [uvicorn.run("mwmbl.tinysearchengine.app:app")](https://github.com/mwmbl/mwmbl/blob/a72a08a7d9cb44213c6ef2c5c203a912cf64bc36/mwmbl/tinysearchengine/app.py#L47) seems to spawn a new process and within that new process the `app` instance is uninitialized.

Due to some python magic behind the scenes, calling [uvicorn.run("mwmbl.tinysearchengine.app:app")](https://github.com/mwmbl/mwmbl/blob/a72a08a7d9cb44213c6ef2c5c203a912cf64bc36/mwmbl/tinysearchengine/app.py#L47) uses the already initialized global `app` instance when using the binary/entrypoint `mwmbl-tinysearchengine ...`.
