### ISSUE TITLE
Unable to run mwmbl locally / index.tinysearch corrupt?

### ISSUE THREAD

**Issue by raypatterson77** [mwmbl/mwmbl#48]
Hi everyone,

I'm trying to run a local development env for mwmbl, but I'm experiencing some difficulties.  
Been following the dev guide: https://github.com/mwmbl/mwmbl/wiki/Development-FAQ

## Steps I've done:
1. Cloning the repo.
```bash
git clone git@github.com:raypatterson77/mwmbl.git
```
3. Setting up Python venv
```bash
python -m venv .     
```
5. Activating Python venv:
```bash
 source bin/activate       
```
7. Install dependencies
```bash
 pip install .        
```
9. Downloaded index File (serveral times) and placed it in data folder
10. Trying to run mwmbl: 
```bash
mwmbl-tinysearchengine --config config/tinysearchengine.yaml  
```
## Errors:
Running
```bash
mwmbl-tinysearchengine --config config/tinysearchengine.yaml  
```
Gives the error:
```bash
usage: mwmbl-tinysearchengine [-h] --index INDEX --terms TERMS
mwmbl-tinysearchengine: error: the following arguments are required: --index, --terms
```
NOTE: /config/tinysearchengine.yaml is not in the master branch, but still available in the update-readme-for-new-crawler branch. Even with /config/tinysearchengine.yaml present, 
```bash
mwmbl-tinysearchengine --config config/tinysearchengine.yaml  
``` 
is failing with the error above.

Trying to use --index --terms paramters as following: 
```bash
mwmbl-tinysearchengine --index data/index.tinysearch --terms data/terms.csv  
```
NOTE: the terms CSV file is nowhere present, not sure about what exactly is expected to be in the file, but from the errors I was getting, 
```bash
term,count
```
needs to be present.  Creating the file terms.csv under data/terms.csv with above content  gives me the error:
```bash
Terms [] []
Traceback (most recent call last):
  File "/home/o/Dokumente/code/python/mwmbl-dev/bin/mwmbl-tinysearchengine", line 8, in <module>
    sys.exit(main())
  File "/home/o/Dokumente/code/python/mwmbl-dev/lib/python3.10/site-packages/mwmbl/tinysearchengine/app.py", line 39, in main
    with TinyIndex(item_factory=Document, index_path=args.index) as tiny_index:
  File "/home/o/Dokumente/code/python/mwmbl-dev/lib/python3.10/site-packages/mwmbl/tinysearchengine/indexer.py", line 81, in __init__
    metadata = TinyIndexMetadata.from_bytes(metadata_bytes)
  File "/home/o/Dokumente/code/python/mwmbl-dev/lib/python3.10/site-packages/mwmbl/tinysearchengine/indexer.py", line 51, in from_bytes
    raise ValueError("This doesn't seem to be an index file")
ValueError: This doesn't seem to be an index file
```

There is no sha sum to validate the integrity of the index.tinysearch file, but as said I downloaded it multiple times and I don't think the file gets corrupted during the download process. 

Am I missing something or is there a problem with the resent version of mwmbl? 
And is there anywhere a example of the terms CSV file?
Is config/tinysearchengine.yaml  for some reason no longer in the master branch? If not I can make a pull requests to add it back from the update-readme-for-new-crawler branch

### Docker
Trying to set up the dev env with docker, ends in similar problems. Unluckily I haven't it documented well, but for building the image config/tinysearchengine.yaml is necessary, as defined in the Dockerfile.
After building: 
```bash
sudo docker run -p 8080:8080 mwmbl                                                                                                                                                                        
usage: mwmbl-tinysearchengine [-h] --index INDEX --terms TERMS
mwmbl-tinysearchengine: error: the following arguments are required: --index, --terms
``` 

### Env
``` bash
uname -a                                                                                                                                                                                                   
Linux o 5.16.7-arch1-1

python --version                                                                                                                                                                                          
Python 3.10.2

pip --version                                                                                                                                                                                                 
pip 21.2.4

docker version                                                                                                                                                                                                
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.5
 Git commit:        e91ed5707e
 Built:             Mon Dec 13 22:31:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Comment by daoudclarke** [comment]
Thanks for the detailed description, will take a look ASAP. Sorry I missed this earlier.

**Comment by omasanori** [comment]
Non-Docker setup still fails, but differently since options have been changed:

```
$ mwmbl-tinysearchengine --help
usage: mwmbl-tinysearchengine [-h] [--data DATA] [--no-background]

mwmbl-tinysearchengine

options:
  -h, --help       show this help message and exit
  --data DATA      Path to the tinysearchengine index file
  --no-background  Disable running the background script to collect data
```

Also, the system requires a database server while the instructions does not mention it.

**Comment by omasanori** [comment]
Docker setup fails, too:

```
$ docker run -p 8080:8080 mwmbl
Creating a new index
Traceback (most recent call last):
  File "/venv/bin/mwmbl-tinysearchengine", line 8, in <module>
    sys.exit(run())
  File "/venv/lib/python3.10/site-packages/mwmbl/main.py", line 51, in run
    TinyIndex.create(item_factory=Document, index_path=index_path, num_pages=NUM_PAGES, page_size=PAGE_SIZE)
  File "/venv/lib/python3.10/site-packages/mwmbl/tinysearchengine/indexer.py", line 204, in create
    with open(index_path, 'wb') as index_file:
FileNotFoundError: [Errno 2] No such file or directory: '/app/storage/index-v2.tinysearch'
```

**Comment by daoudclarke** [comment]
Thanks for this. Hopefully will get to look into it soon.
